# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to="{% media %} '/media/'"),
        ),
    ]
