# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 15:54
from __future__ import unicode_literals

import NewsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_auto_20180106_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to=NewsApp.models.avatar_upload_to),
        ),
    ]
