# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewsApp', '0003_auto_20180106_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField(verbose_name='Текст комментария')),
                ('comments_date', models.DateField(auto_now=True, verbose_name='date')),
                ('comments_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsApp.Articles')),
                ('comments_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
