# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_text',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='comments',
            table=None,
        ),
    ]
