# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0005_auto_20180111_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comments'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_text',
            field=models.TextField(verbose_name='Комментарии'),
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
