# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_auto_20180111_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
    ]
